
export const algeriaLocations = [
  {
    name: 'Adrar',
    baladiyas: [
      'Adrar',
      'Akabli',
      'Aoulef',
      'Reggane',
      'Timimoun',
      'Zaouiet Kounta',
    ],
  },
  {
    name: 'Chlef',
    baladiyas: [
      'Abu El Hassan',
      'Ain Merane',
      'Beni Haoua',
      'Boukadir',
      'Chettia',
      'Chlef',
      'El Karimia',
      'Harchoun',
      'Oued Fodda',
      'Ouled Ben Abdelkader',
      'Ouled Fares',
      'Tadjena',
      'Tenes',
      'Umm Drou',
    ],
  },
  {
    name: 'Laghouat',
    baladiyas: [
      'Aflou',
      'Ain Madhi',
      'Brida',
      'El Ghicha',
      'Gueltat Sidi Saad',
      'Hassi Delaa',
      'Hassi R\'Mel',
      'Ksar El Hirane',
      'Laghouat',
      'Oued Morra',
      'Sidi Bouzid',
    ],
  },
  {
    name: 'Oum El Bouaghi',
    baladiyas: [
      'Ain Babouche',
      'Ain Beida',
      'Ain Diss',
      'Ain Fekroun',
      'Ain Kercha',
      'Ain M\'lila',
      'Behir Chergui',
      'Dhalaa',
      'El Amiria',
      'El Djazia',
      'Fkirina',
      'Hanchir Toumghani',
      'Ksar Sbahi',
      'Meskiana',
      'Oum El Bouaghi',
      'Ouled Hamla',
      'Souk Naamane',
    ],
  },
  { name: 'Batna', baladiyas: ['Arris', 'Batna', 'Barika', 'Merouana', 'N\'Gaous', 'Timgad'] },
  { name: 'Béjaïa', baladiyas: ['Akbou', 'Amizour', 'Barbacha', 'Béjaïa', 'El Kseur', 'Sidi Aich'] },
  { name: 'Biskra', baladiyas: ['Biskra', 'El Kantara', 'Ouled Djellal', 'Sidi Okba', 'Tolga'] },
  { name: 'Béchar', baladiyas: ['Abadla', 'Béchar', 'Beni Ounif', 'Kenadsa', 'Taghit'] },
  { name: 'Blida', baladiyas: ['Blida', 'Boufarik', 'El Affroun', 'Meftah', 'Mouzaia', 'Oued Alleug'] },
  { name: 'Bouira', baladiyas: ['Ain Bessem', 'Bouira', 'Lakhdaria', 'M\'chedallah', 'Sour El Ghozlane'] },
  { name: 'Tamanrasset', baladiyas: ['Abalessa', 'In Guezzam', 'Tamanrasset', 'Tinzaouaten'] },
  { name: 'Tébessa', baladiyas: ['Bir el-Ater', 'Chéria', 'El Aouinet', 'Ouenza', 'Tébessa'] },
  { name: 'Tlemcen', baladiyas: ['Ghazouet', 'Hennaya', 'Maghnia', 'Mansourah', 'Nedroma', 'Remchi', 'Tlemcen'] },
  { name: 'Tiaret', baladiyas: ['Frenda', 'Ksar Chellala', 'Mahdia', 'Sougueur', 'Tiaret'] },
  { name: 'Tizi Ouzou', baladiyas: ['Azazga', 'Beni Douala', 'Draâ Ben Khedda', 'Larbaâ Nath Irathen', 'Tigzirt', 'Tizi Ouzou'] },
  { name: 'Alger', baladiyas: ['Alger Centre', 'Bab Ezzouar', 'Bir Mourad Raïs', 'Chéraga', 'Draria', 'Hussein Dey', 'Kouba', 'Sidi M\'Hamed'] },
  { name: 'Djelfa', baladiyas: ['Ain Oussera', 'Charef', 'Dar Chioukh', 'Djelfa', 'Hassi Bahbah', 'Messaad'] },
  { name: 'Jijel', baladiyas: ['Chekfa', 'El Aouana', 'Jijel', 'Mila', 'Settara', 'Taher'] },
  { name: 'Sétif', baladiyas: ['Ain Arnat', 'Ain Oulmene', 'Amoucha', 'El Eulma', 'Hammam Guergour', 'Sétif'] },
  { name: 'Saïda', baladiyas: ['Ain El Hadjar', 'Hassasna', 'Ouled Brahim', 'Saïda', 'Youb'] },
  { name: 'Skikda', baladiyas: ['Azzaba', 'Ben Azzouz', 'Collo', 'El Harrouch', 'Skikda', 'Tamalous'] },
  { name: 'Sidi Bel Abbès', baladiyas: ['Ain El Berd', 'Marhoum', 'Sidi Ali Boussidi', 'Sidi Bel Abbès', 'Sfisef', 'Tessala'] },
  { name: 'Annaba', baladiyas: ['Annaba', 'Berrahal', 'El Bouni', 'El Hadjar', 'Seraïdi'] },
  { name: 'Guelma', baladiyas: ['Ain Makhlouf', 'Boumahra Ahmed', 'Guelma', 'Hammam Debagh', 'Oued Zenati'] },
  { name: 'Constantine', baladiyas: ['Ain Smara', 'Constantine', 'Didouche Mourad', 'El Khroub', 'Hamma Bouziane'] },
  { name: 'Médéa', baladiyas: ['Berrouaghia', 'Chellalat El Adhaoura', 'Ksar Boukhari', 'Médéa', 'Tablat'] },
  { name: 'Mostaganem', baladiyas: ['Achaacha', 'Ain Tadles', 'Hassi Mameche', 'Mostaganem', 'Sidi Ali'] },
  { name: 'M\'Sila', baladiyas: ['Aïn El Melh', 'Ben Srour', 'Bou Saada', 'Hammam Dhalaâ', 'M\'Sila', 'Sidi Aïssa'] },
  { name: 'Mascara', baladiyas: ['Bouhanifia', 'Ghriss', 'Mascara', 'Mohammadia', 'Sig', 'Tighennif'] },
  { name: 'Ouargla', baladiyas: ['El Borma', 'Hassi Messaoud', 'N\'Goussa', 'Ouargla', 'Touggourt'] },
  { name: 'Oran', baladiyas: ['Ain El Turk', 'Arzew', 'Bir El Djir', 'Es Senia', 'Gdyel', 'Oran'] },
  { name: 'El Bayadh', baladiyas: ['Bougtob', 'Brezina', 'Chellala', 'El Bayadh', 'Rogassa'] },
  { name: 'Illizi', baladiyas: ['Bordj Omar Driss', 'Djanet', 'Illizi', 'In Amenas'] },
  { name: 'Bordj Bou Arreridj', baladiyas: ['Ain Taghrout', 'Bordj Bou Arreridj', 'Bordj Ghedir', 'Ras El Oued'] },
  { name: 'Boumerdès', baladiyas: ['Boudouaou', 'Boumerdès', 'Dellys', 'Khemis El Khechna', 'Thenia'] },
  { name: 'El Tarf', baladiyas: ['Ben Mehidi', 'Besbes', 'Dréan', 'El Kala', 'El Tarf'] },
  { name: 'Tindouf', baladiyas: ['Oum El Assel', 'Tindouf'] },
  { name: 'Tissemsilt', baladiyas: ['Bordj Emir Abdelkader', 'Khemisti', 'Lardjem', 'Theniet El Had', 'Tissemsilt'] },
  { name: 'El Oued', baladiyas: ['Bayadha', 'Debila', 'El Oued', 'Guemar', 'Robbah'] },
  { name: 'Khenchela', baladiyas: ['Bouhmama', 'Chechar', 'El Hamma', 'Khenchela', 'Ouled Rechache'] },
  { name: 'Souk Ahras', baladiyas: ['Heddada', 'M\'daourouch', 'Sedrata', 'Souk Ahras', 'Taoura'] },
  { name: 'Tipaza', baladiyas: ['Cherchell', 'Damous', 'Fouka', 'Hadjout', 'Kolea', 'Tipaza'] },
  { name: 'Mila', baladiyas: ['Chelghoum Laïd', 'Ferdjioua', 'Grarem Gouga', 'Mila', 'Tadjenanet'] },
  { name: 'Aïn Defla', baladiyas: ['Aïn Defla', 'Aïn Lechiekh', 'El Abadia', 'Khemis Miliana', 'Miliana'] },
  { name: 'Naâma', baladiyas: ['Aïn Sefra', 'Asla', 'Mécheria', 'Moghrar', 'Naâma'] },
  { name: 'Aïn Témouchent', baladiyas: ['Aïn Témouchent', 'Beni Saf', 'El Amria', 'Hammam Bouhadjar', 'Oulhaça El Gheraba'] },
  { name: 'Ghardaïa', baladiyas: ['Berriane', 'El Guerrara', 'Ghardaïa', 'Metlili', 'Zelfana'] },
  { name: 'Relizane', baladiyas: ['Ammi Moussa', 'Bendaoud', 'Mazouna', 'Oued Rhiou', 'Relizane', 'Zemmora'] },
  { name: 'Timimoun', baladiyas: ['Timimoun', 'Ouled Said', 'Aougrout', 'Tinerkouk'] },
  { name: 'Bordj Badji Mokhtar', baladiyas: ['Bordj Badji Mokhtar', 'Timiaouine'] },
  { name: 'Ouled Djellal', baladiyas: ['Ouled Djellal', 'Sidi Khaled', 'Besbes'] },
  { name: 'Béni Abbès', baladiyas: ['Béni Abbès', 'Igli', 'Tabelbala', 'Ouled Khoudir'] },
  { name: 'In Salah', baladiyas: ['In Salah', 'Foggaret Ezzaouia', 'In Ghar'] },
  { name: 'In Guezzam', baladiyas: ['In Guezzam', 'Tinzaouten'] },
  { name: 'Touggourt', baladiyas: ['Touggourt', 'Tamacine', 'Blidet Amor', 'Nezla'] },
  { name: 'Djanet', baladiyas: ['Djanet', 'Bordj El Houasse'] },
  { name: 'El M\'Ghair', baladiyas: ['El M\'Ghair', 'Oum Touyour', 'Still'] },
  { name: 'El Meniaa', baladiyas: ['El Meniaa', 'Hassi Gara'] }
];
