[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit MAX30105@^1.2.2
    bblanchon/ArduinoJson@^7.3.1
    tzapu/WiFiManager@^2.0.18
    kriswiner/MAX30105_SPO2@^1.0.0
